### ISSUE TITLE
FR: Add a tag with CTRL-Click/Return

### ISSUE THREAD

**Issue by avirosso** [rwblickhan/obsidian-tag-search#1]
Thanks for this great plugin! 

It could be a powerful replacement for the 'built-in tag pane' if one additional feature would be implemented: To 'add' a tag with CTRL-Click/Return (like in the 'built-in tag pane').

In detail: 

a) Click (or Return): substitutes the search expression in the search pane with the selected tag

b) CTRL-Click (or CTRL-Return): Adds the selected tag to the search expression in the search pane

Thanks in advance!

**Comment by avirosso** [comment]
Thanks for implementing the CTRL-Mouseclick in Release 1.1.0!

But: It doesn't work with CTRL-Return.

It would be great, if you can use also CTRL-Return (don't have to switch from the keyboard to the mouse ...)

Thanks in advance!

**Comment by rwblickhan** [comment]
Ah, you upgraded before I got a chance to respond here 🙈 Glad it's (partly) working for you!

I only noticed that it's not working for Ctrl-Return after submitting the version bump. I'm not totally sure why it doesn't Just Work™️ as-is but I'll take a look this weekend and see if I can get it working.

**Comment by rwblickhan** [comment]
Alrighty, I think I have a (slighty-hacky-but-it-works) fix in [1.2.0](https://github.com/rwblickhan/obsidian-tag-search/releases/tag/1.2.0). I'm going to close this out, but feel free to reopen if it's still not working!

**Comment by avirosso** [comment]
Thanks - unfortunately it doesn't work (tested several times after restart): With the modifier keys (CTRL or/and SHIFT) the FIRST tag in the list (not the actually SELECTED tag in the list) is used ...

**Comment by avirosso** [comment]
How to reopen this issue?

**Comment by rwblickhan** [comment]
There’s a reopen button at the bottom!

My mistake - it’s currently always picking the first item, as you say. I’m not sure if I’m able to get the selection state, actually, but I’ll take another look later this weekend!

**Comment by rwblickhan** [comment]
Okay, I think with [1.2.1](https://github.com/rwblickhan/obsidian-tag-search/releases/tag/1.2.1), this is finally working as expected 😅 although the solution I ended up going with is a little brittle, so it might break with a future Obsidian update - I'll do a bit more investigation at some point to see if there's a better way to do it.

Let me know if it's working for you!

**Comment by avirosso** [comment]
Yes - now it's working! Thank you for this feature!
